# Generated by Django 5.2.15 on 2026-06-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, default='')),
                ('source', models.CharField(choices=[('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('threads', 'Threads'), ('blog', 'Blog / Artículo'), ('podcast', 'Podcast'), ('libro', 'Libro'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('source_custom', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='posts.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
